AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdf_producer

  Sample SAM Template for pdf_producer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  pdfproducerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pdfproducer/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        pdfproducer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pdfproducer
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  pdfproducerApi:
    Description: "API Gateway endpoint URL for Prod stage for pdfproducer function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  pdfproducerFunction:
    Description: "pdfproducer Lambda Function ARN"
    Value: !GetAtt pdfproducerFunction.Arn
  pdfproducerFunctionIamRole:
    Description: "Implicit IAM Role created for pdfproducer function"
    Value: !GetAtt pdfproducerFunctionRole.Arn
