version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf-scan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1urynvzkjcnfr"
s3_prefix = "pdf-scan"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
