AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdf-scan

  Sample SAM Template for pdf-scan

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  pdfscanFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pdfscan/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        pdfscan:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pdfscan
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  pdfscanApi:
    Description: "API Gateway endpoint URL for Prod stage for pdfscan function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pdfscan/"
  pdfscanFunction:
    Description: "pdfscan Lambda Function ARN"
    Value: !GetAtt pdfscanFunction.Arn
  pdfscanFunctionIamRole:
    Description: "Implicit IAM Role created for pdfscan function"
    Value: !GetAtt pdfscanFunctionRole.Arn
